### ISSUE TITLE
not able to screen share 

### ISSUE THREAD

**Issue by DevakiNandanSharma1995** [zoho/AssistSDK#1]
Hello team, 

I have integrated ZoHo SDK in my project. But I am not able to screen share of my iPhone. 
I am not getting any error AssistSession.register(session: id, token: token, appGroup in this function. 

please help me.

**Comment by kishorekumar007** [comment]
Our apologies for the inconvenience. Please share with us your registered email address with Zoho to assist@zohomobile.com. That will help us analyse the issue better.
